### PR TITLE
Add model for the calibrator 3C380

### PR DESCRIPTION
**Pull request by nudomarinero**
Add model for the calibrator 3C380. This calibrator is widely used. I took the model from the COOKBOOK directory in CEP3.

### CODE REVIEW

**Comment by twshimwell** [comment]
Are you sure we have a good model for 3C380 as its a resolved source -- see e.g. http://lofar.strw.leidenuniv.nl/wiki/doku.php?id=g44hba

**Comment by nudomarinero** [comment]
No, I think it is probably not a good model for many purposes, but I am running some tests and thought that it could be better to have this simple model than not having anything at all. 
I kept the MSSS suffix to indicate that it is not a "definitive" source.

**Comment by twshimwell** [comment]
sounds good.

**Comment by AHorneffer** [comment]
All the Scaife & Heald calibrators are in the file "Calibrators_SH_lowres.skymodel".

I'll add the separate skymodels for all those calibrators using my file naming-scheme.

**Comment by nudomarinero** [comment]
OK. Yes, the new naming convention looks better.Thank you.

**Pull request closed without merging**
