### PR TITLE
Modified 3C380 skymodel to high res model. Also added entry in README

### PR DESCRIPTION
**Pull request by cgroeneveld**
Recently, Reinout and I made a 3C380 image with data from Andrea Botteon. We were able to extract a skymodel from the image as well, and although the skymodel is still not perfect, it is at least better than a single point source. This model is probably good enough for the Dutch and potentially few international baselines.

### CODE REVIEW

**Comment by cgroeneveld** [comment]
ds9

**Comment by adrabent** [comment]
@cgroeneveld 
Thank you for the effort and supporting prefactor!
Is your skymodel on the S&H flux density scale?

Alex

**Comment by cgroeneveld** [comment]
Hi!
Yes, this skymodel is fixed to S&H.

Cheers,
Christian

**Comment by twshimwell** [comment]
Great to see. For fixed to S&H - just wondering how the fixing to S&H is being done (are you taking the total flux in your international baseline resolution model and scaling it so that it matches S&H at some frequency and then putting all the spectral stuff in model at some alpha?)

**Comment by cgroeneveld** [comment]
Yes, more or less! I basically made a skymodel from my original image, then determined the total flux, rescaled it to match S&H (77.35 Jy) and set the spectral index in the Spectral Index part. The essential (and potentially flawed) assumption here is that the model doesn't change in morphology/shape between 50 MHz (what I used to make the model) and 150 MHz (the reference for S&H), but I believe the difference is probably not too big.

**Comment by tikk3r** [comment]
Nice image!

> The essential (and potentially flawed) assumption here is that the model doesn't change in morphology/shape between 50 MHz (what I used to make the model) and 150 MHz (the reference for S&H), but I believe the difference is probably not too big.

The Scaife&Heald model goes from 30-300 MHz, so frequency wise you should be able to get a more or less exact flux to scale to from their paper. Morphology-wise it matches what we saw on 10SB HBA data nicely, so I don't think morphology is an issue. It probably just isn't high resolution enough for the full international array at HBA frequencies.

One thing that would be interesting (I think) is to compare the bandpasses you get before adjusting your spectral indices and after you fix them to S&H. I noticed for the HBA model of 3C295 that this has a noticeable effect on their shape.

**Pull request merged**
