### PR TITLE
added proxy capability

### PR DESCRIPTION
**Pull request by amisk**
Added proxy capability.

### CODE REVIEW

**Comment by amisk** [comment]
Just as a comment: It only works if RMExtract also merges the changes into the master.

**Comment by alexmatze** [comment]
So I am running now into an Issue, as referenced. It is complaining about the variable use_proxy, to be referenced before it is assigned. RMExtract and prefactor are the latest versions.

**Comment by maaijke** [comment]
THis problem was solved in the latest commit (3 days ago ) of RMextract.

**Comment by alexmatze** [comment]
Thanks... yeah I confused the versions. All good now

**Pull request merged**
