### PR TITLE
tidy up prefactor

### PR DESCRIPTION
**Pull request by adrabent**

### CODE REVIEW

**Comment by tammojan** [comment]
Thanks for the housekeeping. Where did all the deleted parsets go? I think they were work in progress by @darafferty ?

**Comment by darafferty** [comment]
Hmm --  yes, they are various versions of Initial subtract pipelines and should be kept, I think.

**Comment by adrabent** [comment]
It's only deleted for prefactor v3.0.
I would propose to keep them for the master branch as long as we have not decided how the calibration scheme for the target will be, i.e. there might be a new "Init-Subtract"-version in the future.

**Comment by darafferty** [comment]
Ah -- so you mean we should add them back (or altered versions of them) as we need them? That's fine, though I don't think they will change much in the foreseeable future.

**Comment by adrabent** [comment]
Okay.. maybe I was to harsh, but let me state it like this:

prefactor 3.0 is under development and won't be in production mode soon. I just wanted to keep this branch "empty" and add things back, once they are needed for the pipeline in order to keep it "clean" and not carry things with it which have been used in older versions.

Moreover, while investigating Francesco's [LiLF repository](https://github.com/revoltek/LiLF/tree/master/pipelines) I saw that there is a kind of model subtraction included, but we have not yet discussed with Reinout, FdG, etc. how the new prefactor will do it.

**Pull request merged**
